// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5bP5D8IvINopmgZUWVyq-v_yOZScnzMg',
    appId: '1:401188926833:web:d92ff4b0ea4eceed24b2d0',
    messagingSenderId: '401188926833',
    projectId: 'silent-memory',
    authDomain: 'silent-memory.firebaseapp.com',
    storageBucket: 'silent-memory.firebasestorage.app',
    measurementId: 'G-MZJQFP914R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQbsd87uKIwy_Qy5L-34AjkgcRxGgw94',
    appId: '1:401188926833:android:03e6fe6f16f0775a24b2d0',
    messagingSenderId: '401188926833',
    projectId: 'silent-memory',
    storageBucket: 'silent-memory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrvIArYG3WcwnhLP3sgXdYd70SYLHNKk',
    appId: '1:401188926833:ios:5642aa3078e2513824b2d0',
    messagingSenderId: '401188926833',
    projectId: 'silent-memory',
    storageBucket: 'silent-memory.firebasestorage.app',
    iosBundleId: 'com.example.silentMemoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWrvIArYG3WcwnhLP3sgXdYd70SYLHNKk',
    appId: '1:401188926833:ios:5642aa3078e2513824b2d0',
    messagingSenderId: '401188926833',
    projectId: 'silent-memory',
    storageBucket: 'silent-memory.firebasestorage.app',
    iosBundleId: 'com.example.silentMemoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5bP5D8IvINopmgZUWVyq-v_yOZScnzMg',
    appId: '1:401188926833:web:f0670f7d990d818e24b2d0',
    messagingSenderId: '401188926833',
    projectId: 'silent-memory',
    authDomain: 'silent-memory.firebaseapp.com',
    storageBucket: 'silent-memory.firebasestorage.app',
    measurementId: 'G-KV4G9CGB0G',
  );
}
